================================================================================
Start ./scripts/run_ora_bench_release.sh
--------------------------------------------------------------------------------
OraBench - Release run for VMWare and WSL2.
--------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:22:07
================================================================================
ORACLE_DATABASE_EXISTING : false
ORACLE_DATABASE_18C      : false
ORACLE_DATABASE_19C      : false
ORACLE_DATABASE_21C      : true
--------------------------------------------------------------------------------
RUN_CX_ORACLE_PYTHON     : true
RUN_GODROR_GO            : false
RUN_JDBC_JAVA            : false
RUN_JDBC_JULIA           : false
RUN_JDBC_KOTLIN          : false
RUN_ODPI_C               : false
RUN_ORACLE_JULIA         : false
RUN_ORACLE_RUST          : false
RUN_ORANIF_ELIXIR        : false
RUN_ORANIF_ERLANG        : false
================================================================================
--------------------------------------------------------------------------------
Collect libraries and compile.
--------------------------------------------------------------------------------
==============================================================================
Start scripts/run_collect_and_compile.sh
------------------------------------------------------------------------------
ora_bench - Oracle benchmark - collect libraries and compile.
------------------------------------------------------------------------------
BULKFILE_EXISTING                 : 
------------------------------------------------------------------------------
RUN_CX_ORACLE_PYTHON              : true
RUN_GODROR_GO                     : false
RUN_JDBC_JAVA                     : false
RUN_JDBC_JULIA                    : false
RUN_JDBC_KOTLIN                   : false
RUN_ODPI_C                        : false
RUN_ORACLE_JULIA                  : false
RUN_ORACLE_RUST                   : false
RUN_ORANIF_ELIXIR                 : false
RUN_ORANIF_ERLANG                 : false
------------------------------------------------------------------------------
GOROOT                            : 
GRADLE_HOME                       : 
LD_LIBRARY_PATH                   : /usr/lib/oracle/21/client64/lib:/usr/lib/oracle/21/client64/lib:
------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:22:07
==============================================================================
==============================================================================
Start scripts/run_create_bulk_file.sh
------------------------------------------------------------------------------
ora_bench - Oracle benchmark - setup benchmark run.
------------------------------------------------------------------------------
CHOICE_DRIVER                     : 
------------------------------------------------------------------------------
FILE_CONFIGURATION_NAME           : priv/properties/ora_bench.properties
------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:22:07
==============================================================================
==============================================================================
Start lang/java/scripts/run_gradle.sh
------------------------------------------------------------------------------
ora_bench - Oracle benchmark - Gradle: clean and assemble the Java part of the project.
------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:22:07
==============================================================================
Starting a Gradle Daemon, 2 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Task :init SKIPPED
The build file 'build.gradle' already exists. Skipping build initialization.

BUILD SUCCESSFUL in 2s
> Task :clean

BUILD SUCCESSFUL in 403ms
1 actionable task: 1 executed
> Task :compileJava
> Task :processResources
> Task :classes
> Task :fatJar
> Task :copyJarToLib

BUILD SUCCESSFUL in 2s
4 actionable tasks: 4 executed

------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:22:15
------------------------------------------------------------------------------
End   lang/java/scripts/run_gradle.sh
==============================================================================
2021-10-28 16:22:15,708 [OraBench.java] INFO  Start OraBench.java
2021-10-28 16:22:15,710 [OraBench.java] INFO  main() - number arguments=1
2021-10-28 16:22:15,710 [OraBench.java] INFO  main() - 1st argument=setup
2021-10-28 16:22:15,805 [Config.java] INFO  benchmarkBatchSize      =512
2021-10-28 16:22:15,805 [Config.java] INFO  benchmarkCoreMultiplier =0
2021-10-28 16:22:15,805 [Config.java] INFO  benchmarkTransactionSize=512
2021-10-28 16:22:15,805 [OraBench.java] INFO  Start Setup OraBench Run
2021-10-28 16:22:16,320 [Setup.java] INFO  bulk file written: file name=priv/ora_bench_bulk_data.csv size=100000 length=1024
2021-10-28 16:22:16,321 [Setup.java] INFO  missing result file created: file name=priv/ora_bench_result.tsv
2021-10-28 16:22:16,321 [OraBench.java] INFO  End   Setup OraBench Run
2021-10-28 16:22:16,321 [OraBench.java] INFO  End   OraBench.java

------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:22:16
------------------------------------------------------------------------------
End   scripts/run_create_bulk_file.sh
==============================================================================

------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:22:16
------------------------------------------------------------------------------
End   scripts/run_collect_and_compile.sh
==============================================================================
--------------------------------------------------------------------------------
Create bulk file.
--------------------------------------------------------------------------------
==============================================================================
Start scripts/run_create_bulk_file.sh
------------------------------------------------------------------------------
ora_bench - Oracle benchmark - setup benchmark run.
------------------------------------------------------------------------------
CHOICE_DRIVER                     : 
------------------------------------------------------------------------------
FILE_CONFIGURATION_NAME           : priv/properties/ora_bench.properties
------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:22:16
==============================================================================
==============================================================================
Start lang/java/scripts/run_gradle.sh
------------------------------------------------------------------------------
ora_bench - Oracle benchmark - Gradle: clean and assemble the Java part of the project.
------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:22:16
==============================================================================

> Task :init SKIPPED
The build file 'build.gradle' already exists. Skipping build initialization.

BUILD SUCCESSFUL in 382ms
> Task :clean

BUILD SUCCESSFUL in 371ms
1 actionable task: 1 executed
> Task :compileJava
> Task :processResources
> Task :classes
> Task :fatJar
> Task :copyJarToLib

BUILD SUCCESSFUL in 1s
4 actionable tasks: 4 executed

------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:22:20
------------------------------------------------------------------------------
End   lang/java/scripts/run_gradle.sh
==============================================================================
2021-10-28 16:22:20,848 [OraBench.java] INFO  Start OraBench.java
2021-10-28 16:22:20,849 [OraBench.java] INFO  main() - number arguments=1
2021-10-28 16:22:20,849 [OraBench.java] INFO  main() - 1st argument=setup
2021-10-28 16:22:20,929 [Config.java] INFO  benchmarkBatchSize      =512
2021-10-28 16:22:20,929 [Config.java] INFO  benchmarkCoreMultiplier =0
2021-10-28 16:22:20,930 [Config.java] INFO  benchmarkTransactionSize=512
2021-10-28 16:22:20,930 [OraBench.java] INFO  Start Setup OraBench Run
2021-10-28 16:22:21,451 [Setup.java] INFO  bulk file written: file name=priv/ora_bench_bulk_data.csv size=100000 length=1024
2021-10-28 16:22:21,452 [OraBench.java] INFO  End   Setup OraBench Run
2021-10-28 16:22:21,452 [OraBench.java] INFO  End   OraBench.java

------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:22:21
------------------------------------------------------------------------------
End   scripts/run_create_bulk_file.sh
==============================================================================
--------------------------------------------------------------------------------
Oracle Database 21c.
--------------------------------------------------------------------------------
==============================================================================
Start scripts/run_db_setup.sh
------------------------------------------------------------------------------
ora_bench - Oracle benchmark - database setup.
------------------------------------------------------------------------------
BENCHMARK_DATABASE                : db_21_3_ee
CONNECTION_HOST                   : localhost
CONNECTION_PORT                   : 1521
CONNECTION_SERVICE                : orclpdb1
------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:22:21
==============================================================================
Docker stop/rm ora_bench_db ....................................................
643653a68653   konnexionsgmbh/db_21_3_ee   "/bin/sh -c 'exec $O…"   2 hours ago   Exited (143) About an hour ago                                                                                          ora_bench_db
ora_bench_db
Docker setup network ...........................................................
Deleted Networks:
ora_bench_net

898de747f16d70030f85313ccb821d87806e24735bce8f96f115b25fec468fe0
NETWORK ID     NAME            DRIVER    SCOPE
487a05ddd34b   bridge          bridge    local
83bcf9e02715   host            host      local
f0c486fb1033   none            null      local
898de747f16d   ora_bench_net   bridge    local
Docker create ora_bench_db(db_21_3_ee) ......................
703321736b0d19fcea6fdfc8441a9db01daece864b042ce582dc8ebc4f2d9f0f
Docker started ora_bench_db(db_21_3_ee) .....................
ora_bench_db
CONTAINER ID   IMAGE                       COMMAND                  CREATED        STATUS                                     PORTS                                                 NAMES
703321736b0d   konnexionsgmbh/db_21_3_ee   "/bin/sh -c 'exec $O…"   1 second ago   Up Less than a second (health: starting)   0.0.0.0:1521->1521/tcp, :::1521->1521/tcp, 5500/tcp   ora_bench_db
CONTAINER ID   IMAGE                       COMMAND                  CREATED              STATUS                                 PORTS                                                 NAMES
703321736b0d   konnexionsgmbh/db_21_3_ee   "/bin/sh -c 'exec $O…"   About a minute ago   Up About a minute (health: starting)   0.0.0.0:1521->1521/tcp, :::1521->1521/tcp, 5500/tcp   ora_bench_db
DOCKER ready in 121 seconds .......................................

SQL*Plus: Release 21.0.0.0.0 - Production on Thu Oct 28 16:24:22 2021
Version 21.3.0.0.0

Copyright (c) 1982, 2021, Oracle.  All rights reserved.


Connected to:
Oracle Database 21c Enterprise Edition Release 21.0.0.0.0 - Production
Version 21.3.0.0.0

===============================================================================
Current user is now: SYS
===============================================================================
Start run_db_setup.sql
===============================================================================
Adding database schema SCOTT ...
<------------------------------------------------------------------------------>
Executed: ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE
Executed: CREATE USER SCOTT IDENTIFIED BY regit
===============================================================================
Granting privileges to schema SCOTT ...
<------------------------------------------------------------------------------>
Executed: GRANT ALTER SYSTEM TO SCOTT
Executed: GRANT CREATE PROCEDURE TO SCOTT
Executed: GRANT CREATE SESSION TO SCOTT
Executed: GRANT CREATE TABLE TO SCOTT
Executed: GRANT UNLIMITED TABLESPACE TO SCOTT
Executed: GRANT CREATE TRIGGER TO SCOTT
-------------------------------------------------------------------------------
End   run_db_setup.sql
===============================================================================
Disconnected from Oracle Database 21c Enterprise Edition Release 21.0.0.0.0 - Production
Version 21.3.0.0.0

------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:24:22
------------------------------------------------------------------------------
End   scripts/run_db_setup.sh
==============================================================================
==============================================================================
Start scripts/run_all_drivers.sh
------------------------------------------------------------------------------
ora_bench - Oracle benchmark - all drivers.
------------------------------------------------------------------------------
RUN_CX_ORACLE_PYTHON              : true
RUN_GODROR_GO                     : false
RUN_JDBC_JAVA                     : false
RUN_JDBC_JULIA                    : false
RUN_JDBC_KOTLIN                   : false
RUN_ODPI_C                        : false
RUN_ORACLE_JULIA                  : false
RUN_ORACLE_RUST                   : false
RUN_ORANIF_ELIXIR                 : false
RUN_ORANIF_ERLANG                 : false
------------------------------------------------------------------------------
BENCHMARK_BATCH_SIZE              : 0
BENCHMARK_CORE_MULTIPLIER         : 0
BENCHMARK_TRANSACTION_SIZE        : 0
------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:24:22
==============================================================================
==============================================================================
Start lang/python/scripts/run_bench_cx_oracle.sh
------------------------------------------------------------------------------
ora_bench - Oracle benchmark - cx_Oracle and Python 3.
------------------------------------------------------------------------------
MULTIPLE_RUN                   : 
------------------------------------------------------------------------------
BENCHMARK_DATABASE             : db_21_3_ee
CONNECTION_HOST                : localhost
CONNECTION_PORT                : 1521
CONNECTION_SERVICE             : orclpdb1
------------------------------------------------------------------------------
BENCHMARK_BATCH_SIZE           : 0
BENCHMARK_CORE_MULTIPLIER      : 0
BENCHMARK_TRANSACTION_SIZE     : 0
------------------------------------------------------------------------------
FILE_CONFIGURATION_NAME        : priv/properties/ora_bench.properties
FILE_CONFIGURATION_NAME_PYTHON : priv/properties/ora_bench_python.properties
------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:24:22
==============================================================================
==============================================================================
Start lang/java/scripts/run_gradle.sh
------------------------------------------------------------------------------
ora_bench - Oracle benchmark - Gradle: clean and assemble the Java part of the project.
------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:24:22
==============================================================================

> Task :init SKIPPED
The build file 'build.gradle' already exists. Skipping build initialization.

BUILD SUCCESSFUL in 361ms
> Task :clean

BUILD SUCCESSFUL in 362ms
1 actionable task: 1 executed
> Task :compileJava
> Task :processResources
> Task :classes
> Task :fatJar
> Task :copyJarToLib

BUILD SUCCESSFUL in 1s
4 actionable tasks: 4 executed

------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:24:26
------------------------------------------------------------------------------
End   lang/java/scripts/run_gradle.sh
==============================================================================
2021-10-28 16:24:26,849 [OraBench.java] INFO  Start OraBench.java
2021-10-28 16:24:26,850 [OraBench.java] INFO  main() - number arguments=1
2021-10-28 16:24:26,850 [OraBench.java] INFO  main() - 1st argument=setup_python
2021-10-28 16:24:26,920 [Config.java] INFO  benchmarkBatchSize      =0
2021-10-28 16:24:26,921 [Config.java] INFO  benchmarkCoreMultiplier =0
2021-10-28 16:24:26,921 [Config.java] INFO  benchmarkTransactionSize=0
2021-10-28 16:24:26,921 [OraBench.java] INFO  Start Setup Python 3 OraBench Run
2021-10-28 16:24:26,923 [OraBench.java] INFO  End   Setup Python 3 OraBench Run
2021-10-28 16:24:26,923 [OraBench.java] INFO  End   OraBench.java
Requirement already satisfied: pip in /home/walter/.asdf/installs/python/3.10.0/lib/python3.10/site-packages (21.3.1)
Requirement already satisfied: cx-Oracle in /home/walter/.asdf/installs/python/3.10.0/lib/python3.10/site-packages (from -r lang/python/requirements.txt (line 1)) (8.2.1)
Requirement already satisfied: PyYAML in /home/walter/.asdf/installs/python/3.10.0/lib/python3.10/site-packages (from -r lang/python/requirements.txt (line 2)) (6.0)
=============================================================================> Version Python: 
 
Current version of Python: Python 3.10.0
 
Current version of pip: pip 21.3.1 from /home/walter/.asdf/installs/python/3.10.0/lib/python3.10/site-packages/pip (python 3.10)
 
PyYAML==6.0
 
=============================================================================>
2021-10-28 16:24:29,249 [OraBench.py  ] INFO  Start OraBench.py
2021-10-28 16:24:29,768 [OraBench.py  ] INFO  Start Distribution of the data in the partitions
2021-10-28 16:24:29,768 [OraBench.py  ] INFO  Partition p00000 contains 12.613 rows
2021-10-28 16:24:29,768 [OraBench.py  ] INFO  Partition p00001 contains 12.459 rows
2021-10-28 16:24:29,768 [OraBench.py  ] INFO  Partition p00002 contains 11.972 rows
2021-10-28 16:24:29,768 [OraBench.py  ] INFO  Partition p00003 contains 12.647 rows
2021-10-28 16:24:29,768 [OraBench.py  ] INFO  Partition p00004 contains 13.115 rows
2021-10-28 16:24:29,769 [OraBench.py  ] INFO  Partition p00005 contains 12.446 rows
2021-10-28 16:24:29,769 [OraBench.py  ] INFO  Partition p00006 contains 12.072 rows
2021-10-28 16:24:29,769 [OraBench.py  ] INFO  Partition p00007 contains 12.676 rows
2021-10-28 16:24:29,769 [OraBench.py  ] INFO  End   Distribution of the data in the partitions
2021-10-28 16:24:29,950 [OraBench.py  ] INFO  Start trial no. 1
2021-10-28 16:24:30,042 [OraBench.py  ] INFO  Start insert partition_key=0
2021-10-28 16:24:30,534 [OraBench.py  ] INFO  End   insert partition_ley=0
2021-10-28 16:24:30,534 [OraBench.py  ] INFO  Start insert partition_key=1
2021-10-28 16:24:30,726 [OraBench.py  ] INFO  End   insert partition_ley=1
2021-10-28 16:24:30,727 [OraBench.py  ] INFO  Start insert partition_key=2
2021-10-28 16:24:30,899 [OraBench.py  ] INFO  End   insert partition_ley=2
2021-10-28 16:24:30,900 [OraBench.py  ] INFO  Start insert partition_key=3
2021-10-28 16:24:31,093 [OraBench.py  ] INFO  End   insert partition_ley=3
2021-10-28 16:24:31,094 [OraBench.py  ] INFO  Start insert partition_key=4
2021-10-28 16:24:31,283 [OraBench.py  ] INFO  End   insert partition_ley=4
2021-10-28 16:24:31,283 [OraBench.py  ] INFO  Start insert partition_key=5
2021-10-28 16:24:31,467 [OraBench.py  ] INFO  End   insert partition_ley=5
2021-10-28 16:24:31,468 [OraBench.py  ] INFO  Start insert partition_key=6
2021-10-28 16:24:31,617 [OraBench.py  ] INFO  End   insert partition_ley=6
2021-10-28 16:24:31,618 [OraBench.py  ] INFO  Start insert partition_key=7
2021-10-28 16:24:31,812 [OraBench.py  ] INFO  End   insert partition_ley=7
2021-10-28 16:24:31,813 [OraBench.py  ] INFO  Start select partition_key=0
2021-10-28 16:24:31,868 [OraBench.py  ] INFO  End   select partition_ley=0
2021-10-28 16:24:31,868 [OraBench.py  ] INFO  Start select partition_key=1
2021-10-28 16:24:31,931 [OraBench.py  ] INFO  End   select partition_ley=1
2021-10-28 16:24:31,931 [OraBench.py  ] INFO  Start select partition_key=2
2021-10-28 16:24:32,005 [OraBench.py  ] INFO  End   select partition_ley=2
2021-10-28 16:24:32,005 [OraBench.py  ] INFO  Start select partition_key=3
2021-10-28 16:24:32,051 [OraBench.py  ] INFO  End   select partition_ley=3
2021-10-28 16:24:32,051 [OraBench.py  ] INFO  Start select partition_key=4
2021-10-28 16:24:32,099 [OraBench.py  ] INFO  End   select partition_ley=4
2021-10-28 16:24:32,100 [OraBench.py  ] INFO  Start select partition_key=5
2021-10-28 16:24:32,145 [OraBench.py  ] INFO  End   select partition_ley=5
2021-10-28 16:24:32,145 [OraBench.py  ] INFO  Start select partition_key=6
2021-10-28 16:24:32,189 [OraBench.py  ] INFO  End   select partition_ley=6
2021-10-28 16:24:32,190 [OraBench.py  ] INFO  Start select partition_key=7
2021-10-28 16:24:32,236 [OraBench.py  ] INFO  End   select partition_ley=7
2021-10-28 16:24:32,645 [OraBench.py  ] INFO  Duration (ms) trial         : 2695
2021-10-28 16:24:32,645 [OraBench.py  ] INFO  Start trial no. 2
2021-10-28 16:24:34,648 [OraBench.py  ] INFO  Duration (ms) trial         : 2002
2021-10-28 16:24:34,648 [OraBench.py  ] INFO  Start trial no. 3
2021-10-28 16:24:36,534 [OraBench.py  ] INFO  Duration (ms) trial         : 1886
2021-10-28 16:24:36,534 [OraBench.py  ] INFO  Start trial no. 4
2021-10-28 16:24:38,475 [OraBench.py  ] INFO  Duration (ms) trial         : 1940
2021-10-28 16:24:38,475 [OraBench.py  ] INFO  Start trial no. 5
2021-10-28 16:24:40,450 [OraBench.py  ] INFO  Duration (ms) trial         : 1975
2021-10-28 16:24:40,450 [OraBench.py  ] INFO  Start trial no. 6
2021-10-28 16:24:42,423 [OraBench.py  ] INFO  Duration (ms) trial         : 1973
2021-10-28 16:24:42,424 [OraBench.py  ] INFO  Start trial no. 7
2021-10-28 16:24:44,409 [OraBench.py  ] INFO  Duration (ms) trial         : 1986
2021-10-28 16:24:44,410 [OraBench.py  ] INFO  Start trial no. 8
2021-10-28 16:24:46,374 [OraBench.py  ] INFO  Duration (ms) trial         : 1964
2021-10-28 16:24:46,374 [OraBench.py  ] INFO  Start trial no. 9
2021-10-28 16:24:48,348 [OraBench.py  ] INFO  Duration (ms) trial         : 1973
2021-10-28 16:24:48,348 [OraBench.py  ] INFO  Start trial no. 10
2021-10-28 16:24:50,419 [OraBench.py  ] INFO  Duration (ms) trial         : 2071
2021-10-28 16:24:50,428 [OraBench.py  ] INFO  Duration (ms) trial min.    : 1886
2021-10-28 16:24:50,429 [OraBench.py  ] INFO  Duration (ms) trial max.    : 2695
2021-10-28 16:24:50,429 [OraBench.py  ] INFO  Duration (ms) trial average : 2047
2021-10-28 16:24:50,429 [OraBench.py  ] INFO  Duration (ms) benchmark run : 21178
2021-10-28 16:24:50,481 [OraBench.py  ] INFO  End   OraBench.py

------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:24:50
------------------------------------------------------------------------------
End   lang/python/scripts/run_bench_cx_oracle.sh
==============================================================================
==============================================================================
Start scripts/run_finalise_benchmark.sh
------------------------------------------------------------------------------
ora_bench - Oracle benchmark - finalise benchmark run.
------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:24:50
==============================================================================
2021-10-28 16:24:50,936 [OraBench.java] INFO  Start OraBench.java
2021-10-28 16:24:50,938 [OraBench.java] INFO  main() - number arguments=1
2021-10-28 16:24:50,938 [OraBench.java] INFO  main() - 1st argument=finalise
2021-10-28 16:24:51,012 [Config.java] INFO  benchmarkBatchSize      =0
2021-10-28 16:24:51,012 [Config.java] INFO  benchmarkCoreMultiplier =0
2021-10-28 16:24:51,013 [Config.java] INFO  benchmarkTransactionSize=0
2021-10-28 16:24:51,013 [OraBench.java] INFO  Start Finalise OraBench Run
2021-10-28 16:24:51,020 [Config.java] INFO  benchmarkBatchSize      =0
2021-10-28 16:24:51,020 [Config.java] INFO  benchmarkCoreMultiplier =0
2021-10-28 16:24:51,020 [Config.java] INFO  benchmarkTransactionSize=0
2021-10-28 16:24:51,022 [OraBench.java] INFO  End   Finalise OraBench Run
2021-10-28 16:24:51,022 [OraBench.java] INFO  End   OraBench.java

------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:24:51
------------------------------------------------------------------------------
End   scripts/run_finalise_benchmark.sh
==============================================================================

------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:24:51
------------------------------------------------------------------------------
End   scripts/run_all_drivers.sh
==============================================================================
==============================================================================
Start scripts/run_all_drivers.sh
------------------------------------------------------------------------------
ora_bench - Oracle benchmark - all drivers.
------------------------------------------------------------------------------
RUN_CX_ORACLE_PYTHON              : true
RUN_GODROR_GO                     : false
RUN_JDBC_JAVA                     : false
RUN_JDBC_JULIA                    : false
RUN_JDBC_KOTLIN                   : false
RUN_ODPI_C                        : false
RUN_ORACLE_JULIA                  : false
RUN_ORACLE_RUST                   : false
RUN_ORANIF_ELIXIR                 : false
RUN_ORANIF_ERLANG                 : false
------------------------------------------------------------------------------
BENCHMARK_BATCH_SIZE              : 0
BENCHMARK_CORE_MULTIPLIER         : 1
BENCHMARK_TRANSACTION_SIZE        : 0
------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:24:51
==============================================================================
==============================================================================
Start lang/python/scripts/run_bench_cx_oracle.sh
------------------------------------------------------------------------------
ora_bench - Oracle benchmark - cx_Oracle and Python 3.
------------------------------------------------------------------------------
MULTIPLE_RUN                   : 
------------------------------------------------------------------------------
BENCHMARK_DATABASE             : db_21_3_ee
CONNECTION_HOST                : localhost
CONNECTION_PORT                : 1521
CONNECTION_SERVICE             : orclpdb1
------------------------------------------------------------------------------
BENCHMARK_BATCH_SIZE           : 0
BENCHMARK_CORE_MULTIPLIER      : 1
BENCHMARK_TRANSACTION_SIZE     : 0
------------------------------------------------------------------------------
FILE_CONFIGURATION_NAME        : priv/properties/ora_bench.properties
FILE_CONFIGURATION_NAME_PYTHON : priv/properties/ora_bench_python.properties
------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:24:51
==============================================================================
==============================================================================
Start lang/java/scripts/run_gradle.sh
------------------------------------------------------------------------------
ora_bench - Oracle benchmark - Gradle: clean and assemble the Java part of the project.
------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:24:51
==============================================================================

> Task :init SKIPPED
The build file 'build.gradle' already exists. Skipping build initialization.

BUILD SUCCESSFUL in 379ms
> Task :clean

BUILD SUCCESSFUL in 377ms
1 actionable task: 1 executed
> Task :compileJava
> Task :processResources
> Task :classes
> Task :fatJar
> Task :copyJarToLib

BUILD SUCCESSFUL in 1s
4 actionable tasks: 4 executed

------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:24:55
------------------------------------------------------------------------------
End   lang/java/scripts/run_gradle.sh
==============================================================================
2021-10-28 16:24:55,523 [OraBench.java] INFO  Start OraBench.java
2021-10-28 16:24:55,524 [OraBench.java] INFO  main() - number arguments=1
2021-10-28 16:24:55,525 [OraBench.java] INFO  main() - 1st argument=setup_python
2021-10-28 16:24:55,617 [Config.java] INFO  benchmarkBatchSize      =0
2021-10-28 16:24:55,618 [Config.java] INFO  benchmarkCoreMultiplier =1
2021-10-28 16:24:55,618 [Config.java] INFO  benchmarkTransactionSize=0
2021-10-28 16:24:55,619 [OraBench.java] INFO  Start Setup Python 3 OraBench Run
2021-10-28 16:24:55,620 [OraBench.java] INFO  End   Setup Python 3 OraBench Run
2021-10-28 16:24:55,620 [OraBench.java] INFO  End   OraBench.java
Requirement already satisfied: pip in /home/walter/.asdf/installs/python/3.10.0/lib/python3.10/site-packages (21.3.1)
Requirement already satisfied: cx-Oracle in /home/walter/.asdf/installs/python/3.10.0/lib/python3.10/site-packages (from -r lang/python/requirements.txt (line 1)) (8.2.1)
Requirement already satisfied: PyYAML in /home/walter/.asdf/installs/python/3.10.0/lib/python3.10/site-packages (from -r lang/python/requirements.txt (line 2)) (6.0)
=============================================================================> Version Python: 
 
Current version of Python: Python 3.10.0
 
Current version of pip: pip 21.3.1 from /home/walter/.asdf/installs/python/3.10.0/lib/python3.10/site-packages/pip (python 3.10)
 
PyYAML==6.0
 
=============================================================================>
2021-10-28 16:24:57,919 [OraBench.py  ] INFO  Start OraBench.py
2021-10-28 16:24:58,434 [OraBench.py  ] INFO  Start Distribution of the data in the partitions
2021-10-28 16:24:58,434 [OraBench.py  ] INFO  Partition p00000 contains 12.613 rows
2021-10-28 16:24:58,434 [OraBench.py  ] INFO  Partition p00001 contains 12.459 rows
2021-10-28 16:24:58,434 [OraBench.py  ] INFO  Partition p00002 contains 11.972 rows
2021-10-28 16:24:58,434 [OraBench.py  ] INFO  Partition p00003 contains 12.647 rows
2021-10-28 16:24:58,435 [OraBench.py  ] INFO  Partition p00004 contains 13.115 rows
2021-10-28 16:24:58,435 [OraBench.py  ] INFO  Partition p00005 contains 12.446 rows
2021-10-28 16:24:58,435 [OraBench.py  ] INFO  Partition p00006 contains 12.072 rows
2021-10-28 16:24:58,435 [OraBench.py  ] INFO  Partition p00007 contains 12.676 rows
2021-10-28 16:24:58,435 [OraBench.py  ] INFO  End   Distribution of the data in the partitions
2021-10-28 16:24:58,612 [OraBench.py  ] INFO  Start trial no. 1
Exception in thread Thread-1 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-2 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-3 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-4 (run_insert_helper):
Traceback (most recent call last):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-5 (run_insert_helper):
Exception in thread Thread-7 (run_insert_helper):
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-8 (run_insert_helper):
Traceback (most recent call last):
Traceback (most recent call last):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-6 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-9 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-10 (run_select_helper):
Exception in thread Thread-11 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
Exception in thread Thread-12 (run_select_helper):
Traceback (most recent call last):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-13 (run_select_helper):
Traceback (most recent call last):
Exception in thread Thread-15 (run_select_helper):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-16 (run_select_helper):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-14 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
    self.run()
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
2021-10-28 16:24:58,670 [OraBench.py  ] INFO  Duration (ms) trial         : 58
2021-10-28 16:24:58,670 [OraBench.py  ] INFO  Start trial no. 2
Exception in thread Thread-17 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-18 (run_insert_helper):
Exception in thread Thread-19 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-21 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-20 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-22 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-23 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-24 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-25 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-26 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-28 (run_select_helper):
Exception in thread Thread-30 (run_select_helper):
Traceback (most recent call last):
Exception in thread Thread-29 (run_select_helper):
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
Exception in thread Thread-27 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-31 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-32 (run_select_helper):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
2021-10-28 16:24:58,712 [OraBench.py  ] INFO  Duration (ms) trial         : 41
2021-10-28 16:24:58,712 [OraBench.py  ] INFO  Start trial no. 3
Exception in thread Thread-33 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-34 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-36 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-40 (run_insert_helper):
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-37 (run_insert_helper):
Traceback (most recent call last):
Exception in thread Thread-39 (run_insert_helper):
Traceback (most recent call last):
Exception in thread Thread-38 (run_insert_helper):
Traceback (most recent call last):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-35 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-41 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-42 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-43 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-45 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-46 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-47 (run_select_helper):
    self.run()
Exception in thread Thread-48 (run_select_helper):
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-44 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
2021-10-28 16:24:58,757 [OraBench.py  ] INFO  Duration (ms) trial         : 45
2021-10-28 16:24:58,757 [OraBench.py  ] INFO  Start trial no. 4
Exception in thread Thread-49 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-51 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-50 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-52 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-54 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-53 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
Exception in thread Thread-55 (run_insert_helper):
Exception in thread Thread-56 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-57 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-58 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-59 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-60 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-61 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-64 (run_select_helper):
Exception in thread Thread-62 (run_select_helper):
Traceback (most recent call last):
Exception in thread Thread-63 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
2021-10-28 16:24:58,801 [OraBench.py  ] INFO  Duration (ms) trial         : 44
2021-10-28 16:24:58,801 [OraBench.py  ] INFO  Start trial no. 5
Exception in thread Thread-65 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-66 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-67 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-68 (run_insert_helper):
Traceback (most recent call last):
Exception in thread Thread-70 (run_insert_helper):
Exception in thread Thread-71 (run_insert_helper):
Traceback (most recent call last):
Exception in thread Thread-69 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-72 (run_insert_helper):
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-73 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-74 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
Exception in thread Thread-75 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-78 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-80 (run_select_helper):
Exception in thread Thread-79 (run_select_helper):
Traceback (most recent call last):
Exception in thread Thread-76 (run_select_helper):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-77 (run_select_helper):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
2021-10-28 16:24:58,849 [OraBench.py  ] INFO  Duration (ms) trial         : 49
2021-10-28 16:24:58,850 [OraBench.py  ] INFO  Start trial no. 6
Exception in thread Thread-81 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-82 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-84 (run_insert_helper):
Exception in thread Thread-86 (run_insert_helper):
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-85 (run_insert_helper):
Exception in thread Thread-87 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-88 (run_insert_helper):
Traceback (most recent call last):
Exception in thread Thread-83 (run_insert_helper):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
    self.run()
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    self.run()
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-89 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-90 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-91 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-92 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-94 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-95 (run_select_helper):
Exception in thread Thread-96 (run_select_helper):
Exception in thread Thread-93 (run_select_helper):
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
    self.run()
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    self.run()
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
2021-10-28 16:24:58,894 [OraBench.py  ] INFO  Duration (ms) trial         : 44
2021-10-28 16:24:58,894 [OraBench.py  ] INFO  Start trial no. 7
Exception in thread Thread-97 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-98 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
Exception in thread Thread-102 (run_insert_helper):
Traceback (most recent call last):
Exception in thread Thread-100 (run_insert_helper):
Traceback (most recent call last):
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-99 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-101 (run_insert_helper):
Exception in thread Thread-103 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
Exception in thread Thread-104 (run_insert_helper):
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
    self.run()
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-105 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-106 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-107 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-108 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-109 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-110 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-111 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-112 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
2021-10-28 16:24:58,936 [OraBench.py  ] INFO  Duration (ms) trial         : 42
2021-10-28 16:24:58,936 [OraBench.py  ] INFO  Start trial no. 8
Exception in thread Thread-113 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-114 (run_insert_helper):
Traceback (most recent call last):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-117 (run_insert_helper):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-118 (run_insert_helper):
Exception in thread Thread-115 (run_insert_helper):
Traceback (most recent call last):
Exception in thread Thread-116 (run_insert_helper):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-120 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-119 (run_insert_helper):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-121 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-122 (run_select_helper):
Traceback (most recent call last):
Exception in thread Thread-124 (run_select_helper):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-125 (run_select_helper):
Traceback (most recent call last):
Traceback (most recent call last):
Exception in thread Thread-126 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-127 (run_select_helper):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-128 (run_select_helper):
Traceback (most recent call last):
Exception in thread Thread-123 (run_select_helper):
    self.run()
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
    self.run()
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
2021-10-28 16:24:58,981 [OraBench.py  ] INFO  Duration (ms) trial         : 45
2021-10-28 16:24:58,982 [OraBench.py  ] INFO  Start trial no. 9
Exception in thread Thread-129 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-130 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-131 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-132 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-133 (run_insert_helper):
Exception in thread Thread-134 (run_insert_helper):
Traceback (most recent call last):
Exception in thread Thread-135 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Traceback (most recent call last):
    self.run()
Exception in thread Thread-136 (run_insert_helper):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-137 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-138 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-139 (run_select_helper):
Traceback (most recent call last):
    self.run()
Exception in thread Thread-141 (run_select_helper):
Traceback (most recent call last):
Exception in thread Thread-140 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-142 (run_select_helper):
Traceback (most recent call last):
Exception in thread Thread-144 (run_select_helper):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
Exception in thread Thread-143 (run_select_helper):
Traceback (most recent call last):
    self.run()
    self.run()
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
2021-10-28 16:24:59,024 [OraBench.py  ] INFO  Duration (ms) trial         : 42
2021-10-28 16:24:59,025 [OraBench.py  ] INFO  Start trial no. 10
Exception in thread Thread-145 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-146 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-147 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-148 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-149 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-150 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-151 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-152 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-153 (run_select_helper):
Traceback (most recent call last):
Exception in thread Thread-154 (run_select_helper):
Exception in thread Thread-157 (run_select_helper):
Exception in thread Thread-158 (run_select_helper):
Exception in thread Thread-155 (run_select_helper):
Exception in thread Thread-156 (run_select_helper):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-160 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-159 (run_select_helper):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
    self.run()
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
2021-10-28 16:24:59,067 [OraBench.py  ] INFO  Duration (ms) trial         : 42
2021-10-28 16:24:59,076 [OraBench.py  ] INFO  Duration (ms) trial min.    : 41
2021-10-28 16:24:59,076 [OraBench.py  ] INFO  Duration (ms) trial max.    : 58
2021-10-28 16:24:59,076 [OraBench.py  ] INFO  Duration (ms) trial average : 45
2021-10-28 16:24:59,076 [OraBench.py  ] INFO  Duration (ms) benchmark run : 1157
2021-10-28 16:24:59,133 [OraBench.py  ] INFO  End   OraBench.py

------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:24:59
------------------------------------------------------------------------------
End   lang/python/scripts/run_bench_cx_oracle.sh
==============================================================================
==============================================================================
Start scripts/run_finalise_benchmark.sh
------------------------------------------------------------------------------
ora_bench - Oracle benchmark - finalise benchmark run.
------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:24:59
==============================================================================
2021-10-28 16:24:59,910 [OraBench.java] INFO  Start OraBench.java
2021-10-28 16:24:59,911 [OraBench.java] INFO  main() - number arguments=1
2021-10-28 16:24:59,912 [OraBench.java] INFO  main() - 1st argument=finalise
2021-10-28 16:24:59,983 [Config.java] INFO  benchmarkBatchSize      =0
2021-10-28 16:24:59,983 [Config.java] INFO  benchmarkCoreMultiplier =1
2021-10-28 16:24:59,984 [Config.java] INFO  benchmarkTransactionSize=0
2021-10-28 16:24:59,984 [OraBench.java] INFO  Start Finalise OraBench Run
2021-10-28 16:24:59,991 [Config.java] INFO  benchmarkBatchSize      =0
2021-10-28 16:24:59,991 [Config.java] INFO  benchmarkCoreMultiplier =1
2021-10-28 16:24:59,991 [Config.java] INFO  benchmarkTransactionSize=0
2021-10-28 16:24:59,993 [OraBench.java] INFO  End   Finalise OraBench Run
2021-10-28 16:24:59,993 [OraBench.java] INFO  End   OraBench.java

------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:25:00
------------------------------------------------------------------------------
End   scripts/run_finalise_benchmark.sh
==============================================================================

------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:25:00
------------------------------------------------------------------------------
End   scripts/run_all_drivers.sh
==============================================================================
==============================================================================
Start scripts/run_all_drivers.sh
------------------------------------------------------------------------------
ora_bench - Oracle benchmark - all drivers.
------------------------------------------------------------------------------
RUN_CX_ORACLE_PYTHON              : true
RUN_GODROR_GO                     : false
RUN_JDBC_JAVA                     : false
RUN_JDBC_JULIA                    : false
RUN_JDBC_KOTLIN                   : false
RUN_ODPI_C                        : false
RUN_ORACLE_JULIA                  : false
RUN_ORACLE_RUST                   : false
RUN_ORANIF_ELIXIR                 : false
RUN_ORANIF_ERLANG                 : false
------------------------------------------------------------------------------
BENCHMARK_BATCH_SIZE              : 512
BENCHMARK_CORE_MULTIPLIER         : 0
BENCHMARK_TRANSACTION_SIZE        : 512
------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:25:00
==============================================================================
==============================================================================
Start lang/python/scripts/run_bench_cx_oracle.sh
------------------------------------------------------------------------------
ora_bench - Oracle benchmark - cx_Oracle and Python 3.
------------------------------------------------------------------------------
MULTIPLE_RUN                   : 
------------------------------------------------------------------------------
BENCHMARK_DATABASE             : db_21_3_ee
CONNECTION_HOST                : localhost
CONNECTION_PORT                : 1521
CONNECTION_SERVICE             : orclpdb1
------------------------------------------------------------------------------
BENCHMARK_BATCH_SIZE           : 512
BENCHMARK_CORE_MULTIPLIER      : 0
BENCHMARK_TRANSACTION_SIZE     : 512
------------------------------------------------------------------------------
FILE_CONFIGURATION_NAME        : priv/properties/ora_bench.properties
FILE_CONFIGURATION_NAME_PYTHON : priv/properties/ora_bench_python.properties
------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:25:00
==============================================================================
==============================================================================
Start lang/java/scripts/run_gradle.sh
------------------------------------------------------------------------------
ora_bench - Oracle benchmark - Gradle: clean and assemble the Java part of the project.
------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:25:00
==============================================================================

> Task :init SKIPPED
The build file 'build.gradle' already exists. Skipping build initialization.

BUILD SUCCESSFUL in 369ms
> Task :clean

BUILD SUCCESSFUL in 382ms
1 actionable task: 1 executed
> Task :compileJava
> Task :processResources
> Task :classes
> Task :fatJar
> Task :copyJarToLib

BUILD SUCCESSFUL in 1s
4 actionable tasks: 4 executed

------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:25:04
------------------------------------------------------------------------------
End   lang/java/scripts/run_gradle.sh
==============================================================================
2021-10-28 16:25:04,506 [OraBench.java] INFO  Start OraBench.java
2021-10-28 16:25:04,508 [OraBench.java] INFO  main() - number arguments=1
2021-10-28 16:25:04,508 [OraBench.java] INFO  main() - 1st argument=setup_python
2021-10-28 16:25:04,596 [Config.java] INFO  benchmarkBatchSize      =512
2021-10-28 16:25:04,596 [Config.java] INFO  benchmarkCoreMultiplier =0
2021-10-28 16:25:04,597 [Config.java] INFO  benchmarkTransactionSize=512
2021-10-28 16:25:04,597 [OraBench.java] INFO  Start Setup Python 3 OraBench Run
2021-10-28 16:25:04,598 [OraBench.java] INFO  End   Setup Python 3 OraBench Run
2021-10-28 16:25:04,598 [OraBench.java] INFO  End   OraBench.java
Requirement already satisfied: pip in /home/walter/.asdf/installs/python/3.10.0/lib/python3.10/site-packages (21.3.1)
Requirement already satisfied: cx-Oracle in /home/walter/.asdf/installs/python/3.10.0/lib/python3.10/site-packages (from -r lang/python/requirements.txt (line 1)) (8.2.1)
Requirement already satisfied: PyYAML in /home/walter/.asdf/installs/python/3.10.0/lib/python3.10/site-packages (from -r lang/python/requirements.txt (line 2)) (6.0)
=============================================================================> Version Python: 
 
Current version of Python: Python 3.10.0
 
Current version of pip: pip 21.3.1 from /home/walter/.asdf/installs/python/3.10.0/lib/python3.10/site-packages/pip (python 3.10)
 
PyYAML==6.0
 
=============================================================================>
2021-10-28 16:25:06,843 [OraBench.py  ] INFO  Start OraBench.py
2021-10-28 16:25:07,345 [OraBench.py  ] INFO  Start Distribution of the data in the partitions
2021-10-28 16:25:07,345 [OraBench.py  ] INFO  Partition p00000 contains 12.613 rows
2021-10-28 16:25:07,345 [OraBench.py  ] INFO  Partition p00001 contains 12.459 rows
2021-10-28 16:25:07,345 [OraBench.py  ] INFO  Partition p00002 contains 11.972 rows
2021-10-28 16:25:07,345 [OraBench.py  ] INFO  Partition p00003 contains 12.647 rows
2021-10-28 16:25:07,345 [OraBench.py  ] INFO  Partition p00004 contains 13.115 rows
2021-10-28 16:25:07,345 [OraBench.py  ] INFO  Partition p00005 contains 12.446 rows
2021-10-28 16:25:07,345 [OraBench.py  ] INFO  Partition p00006 contains 12.072 rows
2021-10-28 16:25:07,345 [OraBench.py  ] INFO  Partition p00007 contains 12.676 rows
2021-10-28 16:25:07,345 [OraBench.py  ] INFO  End   Distribution of the data in the partitions
2021-10-28 16:25:07,514 [OraBench.py  ] INFO  Start trial no. 1
2021-10-28 16:25:07,533 [OraBench.py  ] INFO  Start insert partition_key=0
2021-10-28 16:25:07,744 [OraBench.py  ] INFO  End   insert partition_ley=0
2021-10-28 16:25:07,744 [OraBench.py  ] INFO  Start insert partition_key=1
2021-10-28 16:25:07,928 [OraBench.py  ] INFO  End   insert partition_ley=1
2021-10-28 16:25:07,928 [OraBench.py  ] INFO  Start insert partition_key=2
2021-10-28 16:25:08,103 [OraBench.py  ] INFO  End   insert partition_ley=2
2021-10-28 16:25:08,103 [OraBench.py  ] INFO  Start insert partition_key=3
2021-10-28 16:25:08,295 [OraBench.py  ] INFO  End   insert partition_ley=3
2021-10-28 16:25:08,295 [OraBench.py  ] INFO  Start insert partition_key=4
2021-10-28 16:25:08,483 [OraBench.py  ] INFO  End   insert partition_ley=4
2021-10-28 16:25:08,483 [OraBench.py  ] INFO  Start insert partition_key=5
2021-10-28 16:25:08,665 [OraBench.py  ] INFO  End   insert partition_ley=5
2021-10-28 16:25:08,665 [OraBench.py  ] INFO  Start insert partition_key=6
2021-10-28 16:25:08,859 [OraBench.py  ] INFO  End   insert partition_ley=6
2021-10-28 16:25:08,860 [OraBench.py  ] INFO  Start insert partition_key=7
2021-10-28 16:25:09,052 [OraBench.py  ] INFO  End   insert partition_ley=7
2021-10-28 16:25:09,052 [OraBench.py  ] INFO  Start select partition_key=0
2021-10-28 16:25:09,109 [OraBench.py  ] INFO  End   select partition_ley=0
2021-10-28 16:25:09,110 [OraBench.py  ] INFO  Start select partition_key=1
2021-10-28 16:25:09,158 [OraBench.py  ] INFO  End   select partition_ley=1
2021-10-28 16:25:09,159 [OraBench.py  ] INFO  Start select partition_key=2
2021-10-28 16:25:09,211 [OraBench.py  ] INFO  End   select partition_ley=2
2021-10-28 16:25:09,211 [OraBench.py  ] INFO  Start select partition_key=3
2021-10-28 16:25:09,260 [OraBench.py  ] INFO  End   select partition_ley=3
2021-10-28 16:25:09,260 [OraBench.py  ] INFO  Start select partition_key=4
2021-10-28 16:25:09,310 [OraBench.py  ] INFO  End   select partition_ley=4
2021-10-28 16:25:09,310 [OraBench.py  ] INFO  Start select partition_key=5
2021-10-28 16:25:09,355 [OraBench.py  ] INFO  End   select partition_ley=5
2021-10-28 16:25:09,355 [OraBench.py  ] INFO  Start select partition_key=6
2021-10-28 16:25:09,399 [OraBench.py  ] INFO  End   select partition_ley=6
2021-10-28 16:25:09,399 [OraBench.py  ] INFO  Start select partition_key=7
2021-10-28 16:25:09,443 [OraBench.py  ] INFO  End   select partition_ley=7
2021-10-28 16:25:09,740 [OraBench.py  ] INFO  Duration (ms) trial         : 2226
2021-10-28 16:25:09,741 [OraBench.py  ] INFO  Start trial no. 2
2021-10-28 16:25:11,939 [OraBench.py  ] INFO  Duration (ms) trial         : 2198
2021-10-28 16:25:11,939 [OraBench.py  ] INFO  Start trial no. 3
2021-10-28 16:25:14,117 [OraBench.py  ] INFO  Duration (ms) trial         : 2177
2021-10-28 16:25:14,117 [OraBench.py  ] INFO  Start trial no. 4
2021-10-28 16:25:16,237 [OraBench.py  ] INFO  Duration (ms) trial         : 2120
2021-10-28 16:25:16,237 [OraBench.py  ] INFO  Start trial no. 5
2021-10-28 16:25:18,362 [OraBench.py  ] INFO  Duration (ms) trial         : 2125
2021-10-28 16:25:18,363 [OraBench.py  ] INFO  Start trial no. 6
2021-10-28 16:25:20,482 [OraBench.py  ] INFO  Duration (ms) trial         : 2119
2021-10-28 16:25:20,483 [OraBench.py  ] INFO  Start trial no. 7
2021-10-28 16:25:22,600 [OraBench.py  ] INFO  Duration (ms) trial         : 2118
2021-10-28 16:25:22,600 [OraBench.py  ] INFO  Start trial no. 8
2021-10-28 16:25:24,696 [OraBench.py  ] INFO  Duration (ms) trial         : 2096
2021-10-28 16:25:24,697 [OraBench.py  ] INFO  Start trial no. 9
2021-10-28 16:25:26,818 [OraBench.py  ] INFO  Duration (ms) trial         : 2121
2021-10-28 16:25:26,818 [OraBench.py  ] INFO  Start trial no. 10
2021-10-28 16:25:28,937 [OraBench.py  ] INFO  Duration (ms) trial         : 2119
2021-10-28 16:25:28,946 [OraBench.py  ] INFO  Duration (ms) trial min.    : 2096
2021-10-28 16:25:28,946 [OraBench.py  ] INFO  Duration (ms) trial max.    : 2226
2021-10-28 16:25:28,946 [OraBench.py  ] INFO  Duration (ms) trial average : 2142
2021-10-28 16:25:28,947 [OraBench.py  ] INFO  Duration (ms) benchmark run : 22103
2021-10-28 16:25:29,005 [OraBench.py  ] INFO  End   OraBench.py

------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:25:29
------------------------------------------------------------------------------
End   lang/python/scripts/run_bench_cx_oracle.sh
==============================================================================
==============================================================================
Start scripts/run_finalise_benchmark.sh
------------------------------------------------------------------------------
ora_bench - Oracle benchmark - finalise benchmark run.
------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:25:29
==============================================================================
2021-10-28 16:25:29,461 [OraBench.java] INFO  Start OraBench.java
2021-10-28 16:25:29,463 [OraBench.java] INFO  main() - number arguments=1
2021-10-28 16:25:29,463 [OraBench.java] INFO  main() - 1st argument=finalise
2021-10-28 16:25:29,538 [Config.java] INFO  benchmarkBatchSize      =512
2021-10-28 16:25:29,539 [Config.java] INFO  benchmarkCoreMultiplier =0
2021-10-28 16:25:29,539 [Config.java] INFO  benchmarkTransactionSize=512
2021-10-28 16:25:29,539 [OraBench.java] INFO  Start Finalise OraBench Run
2021-10-28 16:25:29,546 [Config.java] INFO  benchmarkBatchSize      =512
2021-10-28 16:25:29,547 [Config.java] INFO  benchmarkCoreMultiplier =0
2021-10-28 16:25:29,547 [Config.java] INFO  benchmarkTransactionSize=512
2021-10-28 16:25:29,549 [OraBench.java] INFO  End   Finalise OraBench Run
2021-10-28 16:25:29,549 [OraBench.java] INFO  End   OraBench.java

------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:25:29
------------------------------------------------------------------------------
End   scripts/run_finalise_benchmark.sh
==============================================================================

------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:25:29
------------------------------------------------------------------------------
End   scripts/run_all_drivers.sh
==============================================================================
==============================================================================
Start scripts/run_all_drivers.sh
------------------------------------------------------------------------------
ora_bench - Oracle benchmark - all drivers.
------------------------------------------------------------------------------
RUN_CX_ORACLE_PYTHON              : true
RUN_GODROR_GO                     : false
RUN_JDBC_JAVA                     : false
RUN_JDBC_JULIA                    : false
RUN_JDBC_KOTLIN                   : false
RUN_ODPI_C                        : false
RUN_ORACLE_JULIA                  : false
RUN_ORACLE_RUST                   : false
RUN_ORANIF_ELIXIR                 : false
RUN_ORANIF_ERLANG                 : false
------------------------------------------------------------------------------
BENCHMARK_BATCH_SIZE              : 512
BENCHMARK_CORE_MULTIPLIER         : 1
BENCHMARK_TRANSACTION_SIZE        : 512
------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:25:29
==============================================================================
==============================================================================
Start lang/python/scripts/run_bench_cx_oracle.sh
------------------------------------------------------------------------------
ora_bench - Oracle benchmark - cx_Oracle and Python 3.
------------------------------------------------------------------------------
MULTIPLE_RUN                   : 
------------------------------------------------------------------------------
BENCHMARK_DATABASE             : db_21_3_ee
CONNECTION_HOST                : localhost
CONNECTION_PORT                : 1521
CONNECTION_SERVICE             : orclpdb1
------------------------------------------------------------------------------
BENCHMARK_BATCH_SIZE           : 512
BENCHMARK_CORE_MULTIPLIER      : 1
BENCHMARK_TRANSACTION_SIZE     : 512
------------------------------------------------------------------------------
FILE_CONFIGURATION_NAME        : priv/properties/ora_bench.properties
FILE_CONFIGURATION_NAME_PYTHON : priv/properties/ora_bench_python.properties
------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:25:29
==============================================================================
==============================================================================
Start lang/java/scripts/run_gradle.sh
------------------------------------------------------------------------------
ora_bench - Oracle benchmark - Gradle: clean and assemble the Java part of the project.
------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:25:29
==============================================================================

> Task :init SKIPPED
The build file 'build.gradle' already exists. Skipping build initialization.

BUILD SUCCESSFUL in 402ms
> Task :clean

BUILD SUCCESSFUL in 375ms
1 actionable task: 1 executed
> Task :compileJava
> Task :processResources
> Task :classes
> Task :fatJar
> Task :copyJarToLib

BUILD SUCCESSFUL in 1s
4 actionable tasks: 4 executed

------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:25:33
------------------------------------------------------------------------------
End   lang/java/scripts/run_gradle.sh
==============================================================================
2021-10-28 16:25:33,985 [OraBench.java] INFO  Start OraBench.java
2021-10-28 16:25:33,986 [OraBench.java] INFO  main() - number arguments=1
2021-10-28 16:25:33,986 [OraBench.java] INFO  main() - 1st argument=setup_python
2021-10-28 16:25:34,081 [Config.java] INFO  benchmarkBatchSize      =512
2021-10-28 16:25:34,081 [Config.java] INFO  benchmarkCoreMultiplier =1
2021-10-28 16:25:34,081 [Config.java] INFO  benchmarkTransactionSize=512
2021-10-28 16:25:34,082 [OraBench.java] INFO  Start Setup Python 3 OraBench Run
2021-10-28 16:25:34,083 [OraBench.java] INFO  End   Setup Python 3 OraBench Run
2021-10-28 16:25:34,083 [OraBench.java] INFO  End   OraBench.java
Requirement already satisfied: pip in /home/walter/.asdf/installs/python/3.10.0/lib/python3.10/site-packages (21.3.1)
Requirement already satisfied: cx-Oracle in /home/walter/.asdf/installs/python/3.10.0/lib/python3.10/site-packages (from -r lang/python/requirements.txt (line 1)) (8.2.1)
Requirement already satisfied: PyYAML in /home/walter/.asdf/installs/python/3.10.0/lib/python3.10/site-packages (from -r lang/python/requirements.txt (line 2)) (6.0)
=============================================================================> Version Python: 
 
Current version of Python: Python 3.10.0
 
Current version of pip: pip 21.3.1 from /home/walter/.asdf/installs/python/3.10.0/lib/python3.10/site-packages/pip (python 3.10)
 
PyYAML==6.0
 
=============================================================================>
2021-10-28 16:25:36,307 [OraBench.py  ] INFO  Start OraBench.py
2021-10-28 16:25:36,803 [OraBench.py  ] INFO  Start Distribution of the data in the partitions
2021-10-28 16:25:36,803 [OraBench.py  ] INFO  Partition p00000 contains 12.613 rows
2021-10-28 16:25:36,804 [OraBench.py  ] INFO  Partition p00001 contains 12.459 rows
2021-10-28 16:25:36,804 [OraBench.py  ] INFO  Partition p00002 contains 11.972 rows
2021-10-28 16:25:36,804 [OraBench.py  ] INFO  Partition p00003 contains 12.647 rows
2021-10-28 16:25:36,804 [OraBench.py  ] INFO  Partition p00004 contains 13.115 rows
2021-10-28 16:25:36,804 [OraBench.py  ] INFO  Partition p00005 contains 12.446 rows
2021-10-28 16:25:36,804 [OraBench.py  ] INFO  Partition p00006 contains 12.072 rows
2021-10-28 16:25:36,804 [OraBench.py  ] INFO  Partition p00007 contains 12.676 rows
2021-10-28 16:25:36,804 [OraBench.py  ] INFO  End   Distribution of the data in the partitions
2021-10-28 16:25:36,989 [OraBench.py  ] INFO  Start trial no. 1
Exception in thread Thread-1 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-2 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-6 (run_insert_helper):
Traceback (most recent call last):
Exception in thread Thread-4 (run_insert_helper):
Exception in thread Thread-3 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-8 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-5 (run_insert_helper):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Traceback (most recent call last):
Exception in thread Thread-7 (run_insert_helper):
    self.run()
    self.run()
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-9 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-12 (run_select_helper):
Traceback (most recent call last):
Exception in thread Thread-13 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-16 (run_select_helper):
Exception in thread Thread-14 (run_select_helper):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-11 (run_select_helper):
Exception in thread Thread-10 (run_select_helper):
Exception in thread Thread-15 (run_select_helper):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
2021-10-28 16:25:37,042 [OraBench.py  ] INFO  Duration (ms) trial         : 53
2021-10-28 16:25:37,042 [OraBench.py  ] INFO  Start trial no. 2
Exception in thread Thread-17 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-18 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-20 (run_insert_helper):
Traceback (most recent call last):
Exception in thread Thread-22 (run_insert_helper):
Traceback (most recent call last):
Exception in thread Thread-21 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-19 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-24 (run_insert_helper):
Exception in thread Thread-23 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Traceback (most recent call last):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-25 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-26 (run_select_helper):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-27 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-28 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-30 (run_select_helper):
Exception in thread Thread-31 (run_select_helper):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-29 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-32 (run_select_helper):
    self.run()
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
2021-10-28 16:25:37,085 [OraBench.py  ] INFO  Duration (ms) trial         : 43
2021-10-28 16:25:37,085 [OraBench.py  ] INFO  Start trial no. 3
Exception in thread Thread-33 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-34 (run_insert_helper):
Exception in thread Thread-35 (run_insert_helper):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-38 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-37 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-36 (run_insert_helper):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-40 (run_insert_helper):
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-39 (run_insert_helper):
    self.run()
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-41 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-43 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-44 (run_select_helper):
Exception in thread Thread-42 (run_select_helper):
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-46 (run_select_helper):
Traceback (most recent call last):
Exception in thread Thread-48 (run_select_helper):
Exception in thread Thread-45 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-47 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
2021-10-28 16:25:37,132 [OraBench.py  ] INFO  Duration (ms) trial         : 46
2021-10-28 16:25:37,132 [OraBench.py  ] INFO  Start trial no. 4
Exception in thread Thread-49 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-50 (run_insert_helper):
Traceback (most recent call last):
Exception in thread Thread-51 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
Exception in thread Thread-53 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-54 (run_insert_helper):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-55 (run_insert_helper):
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-56 (run_insert_helper):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-52 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-57 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-58 (run_select_helper):
Traceback (most recent call last):
Exception in thread Thread-59 (run_select_helper):
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-61 (run_select_helper):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-63 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-60 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-62 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
Exception in thread Thread-64 (run_select_helper):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
2021-10-28 16:25:37,178 [OraBench.py  ] INFO  Duration (ms) trial         : 46
2021-10-28 16:25:37,179 [OraBench.py  ] INFO  Start trial no. 5
Exception in thread Thread-65 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-66 (run_insert_helper):
Traceback (most recent call last):
Exception in thread Thread-67 (run_insert_helper):
Exception in thread Thread-70 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-68 (run_insert_helper):
Exception in thread Thread-72 (run_insert_helper):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
Exception in thread Thread-71 (run_insert_helper):
Traceback (most recent call last):
Traceback (most recent call last):
Exception in thread Thread-69 (run_insert_helper):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Traceback (most recent call last):
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-73 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-74 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-77 (run_select_helper):
Traceback (most recent call last):
Exception in thread Thread-78 (run_select_helper):
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-75 (run_select_helper):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-76 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
    self._target(*self._args, **self._kwargs)
Exception in thread Thread-80 (run_select_helper):
Traceback (most recent call last):
Exception in thread Thread-79 (run_select_helper):
Traceback (most recent call last):
    self.run()
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
    self._target(*self._args, **self._kwargs)
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
2021-10-28 16:25:37,222 [OraBench.py  ] INFO  Duration (ms) trial         : 44
2021-10-28 16:25:37,222 [OraBench.py  ] INFO  Start trial no. 6
Exception in thread Thread-81 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-82 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-83 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-86 (run_insert_helper):
    self._target(*self._args, **self._kwargs)
Exception in thread Thread-85 (run_insert_helper):
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-84 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-88 (run_insert_helper):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
Exception in thread Thread-87 (run_insert_helper):
Traceback (most recent call last):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
    self.run()
    self._target(*self._args, **self._kwargs)
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-89 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-90 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-91 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-92 (run_select_helper):
Traceback (most recent call last):
    self.run()
    self.run()
Exception in thread Thread-94 (run_select_helper):
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-95 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-96 (run_select_helper):
Exception in thread Thread-93 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
    self.run()
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
2021-10-28 16:25:37,268 [OraBench.py  ] INFO  Duration (ms) trial         : 45
2021-10-28 16:25:37,268 [OraBench.py  ] INFO  Start trial no. 7
Exception in thread Thread-97 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-98 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-99 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-101 (run_insert_helper):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-100 (run_insert_helper):
Exception in thread Thread-103 (run_insert_helper):
Traceback (most recent call last):
    self.run()
Traceback (most recent call last):
Exception in thread Thread-104 (run_insert_helper):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-102 (run_insert_helper):
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Traceback (most recent call last):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-105 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-106 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-107 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-108 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-109 (run_select_helper):
Exception in thread Thread-110 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-112 (run_select_helper):
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
Exception in thread Thread-111 (run_select_helper):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
2021-10-28 16:25:37,313 [OraBench.py  ] INFO  Duration (ms) trial         : 45
2021-10-28 16:25:37,313 [OraBench.py  ] INFO  Start trial no. 8
Exception in thread Thread-113 (run_insert_helper):
Traceback (most recent call last):
Exception in thread Thread-114 (run_insert_helper):
Exception in thread Thread-115 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-116 (run_insert_helper):
Exception in thread Thread-118 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-117 (run_insert_helper):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-119 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-120 (run_insert_helper):
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-121 (run_select_helper):
Exception in thread Thread-122 (run_select_helper):
Traceback (most recent call last):
Exception in thread Thread-123 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-124 (run_select_helper):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-125 (run_select_helper):
Traceback (most recent call last):
    self.run()
Exception in thread Thread-126 (run_select_helper):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
Exception in thread Thread-127 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-128 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
2021-10-28 16:25:37,358 [OraBench.py  ] INFO  Duration (ms) trial         : 45
2021-10-28 16:25:37,358 [OraBench.py  ] INFO  Start trial no. 9
Exception in thread Thread-129 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-130 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
Exception in thread Thread-133 (run_insert_helper):
Traceback (most recent call last):
Exception in thread Thread-132 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-131 (run_insert_helper):
Exception in thread Thread-134 (run_insert_helper):
Exception in thread Thread-136 (run_insert_helper):
Traceback (most recent call last):
Exception in thread Thread-135 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
    self.run()
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-137 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-138 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
Exception in thread Thread-139 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-140 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-141 (run_select_helper):
Exception in thread Thread-142 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
Exception in thread Thread-143 (run_select_helper):
    self.run()
Exception in thread Thread-144 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
2021-10-28 16:25:37,401 [OraBench.py  ] INFO  Duration (ms) trial         : 43
2021-10-28 16:25:37,402 [OraBench.py  ] INFO  Start trial no. 10
Exception in thread Thread-145 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-146 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-147 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-151 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-148 (run_insert_helper):
Traceback (most recent call last):
Exception in thread Thread-149 (run_insert_helper):
Traceback (most recent call last):
Exception in thread Thread-152 (run_insert_helper):
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-150 (run_insert_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_insert_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-153 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-154 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-155 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-156 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-157 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-158 (run_select_helper):
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self._target(*self._args, **self._kwargs)
Exception in thread Thread-159 (run_select_helper):
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
Exception in thread Thread-160 (run_select_helper):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
Traceback (most recent call last):
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
    self.run()
  File "/home/walter/.asdf/installs/python/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: run_select_helper() missing 1 required positional argument: 'trial_number'
2021-10-28 16:25:37,445 [OraBench.py  ] INFO  Duration (ms) trial         : 43
2021-10-28 16:25:37,452 [OraBench.py  ] INFO  Duration (ms) trial min.    : 43
2021-10-28 16:25:37,452 [OraBench.py  ] INFO  Duration (ms) trial max.    : 53
2021-10-28 16:25:37,453 [OraBench.py  ] INFO  Duration (ms) trial average : 45
2021-10-28 16:25:37,453 [OraBench.py  ] INFO  Duration (ms) benchmark run : 1145
2021-10-28 16:25:37,508 [OraBench.py  ] INFO  End   OraBench.py

------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:25:37
------------------------------------------------------------------------------
End   lang/python/scripts/run_bench_cx_oracle.sh
==============================================================================
==============================================================================
Start scripts/run_finalise_benchmark.sh
------------------------------------------------------------------------------
ora_bench - Oracle benchmark - finalise benchmark run.
------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:25:37
==============================================================================
2021-10-28 16:25:38,275 [OraBench.java] INFO  Start OraBench.java
2021-10-28 16:25:38,277 [OraBench.java] INFO  main() - number arguments=1
2021-10-28 16:25:38,277 [OraBench.java] INFO  main() - 1st argument=finalise
2021-10-28 16:25:38,349 [Config.java] INFO  benchmarkBatchSize      =512
2021-10-28 16:25:38,349 [Config.java] INFO  benchmarkCoreMultiplier =1
2021-10-28 16:25:38,349 [Config.java] INFO  benchmarkTransactionSize=512
2021-10-28 16:25:38,350 [OraBench.java] INFO  Start Finalise OraBench Run
2021-10-28 16:25:38,357 [Config.java] INFO  benchmarkBatchSize      =512
2021-10-28 16:25:38,357 [Config.java] INFO  benchmarkCoreMultiplier =1
2021-10-28 16:25:38,357 [Config.java] INFO  benchmarkTransactionSize=512
2021-10-28 16:25:38,359 [OraBench.java] INFO  End   Finalise OraBench Run
2021-10-28 16:25:38,359 [OraBench.java] INFO  End   OraBench.java

------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:25:38
------------------------------------------------------------------------------
End   scripts/run_finalise_benchmark.sh
==============================================================================

------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:25:38
------------------------------------------------------------------------------
End   scripts/run_all_drivers.sh
==============================================================================
--------------------------------------------------------------------------------
DATE TIME : 28.10.2021 16:25:38
--------------------------------------------------------------------------------
End   ./scripts/run_ora_bench_release.sh
================================================================================
